In [1]:
import numpy as np
import pandas as pd

In [2]:
car = pd.read_csv('./mtcars.csv')
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [3]:
car

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [4]:
# qsec 컬럼을 최소최대 척도(Min-Max Scale)로 변환 qsec_mm
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
minmax.fit(car['qsec'].values.reshape(-1,1))
res = minmax.transform(car['qsec'].values.reshape(-1,1))
car['qsec_mm'] = res
car

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,qsec_mm
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0.233333
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,0.300000
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,0.489286
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,0.588095
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,0.300000
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1,0.680952
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4,0.159524
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2,0.654762
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2,1.000000
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4,0.452381
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4,0.523810
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3,0.345238
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3,0.369048
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3,0.416667
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4,0.414286
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4,0.395238
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4,0.347619
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,0.591667
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,0.478571
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,0.642857
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1,0.655952
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2,0.282143
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2,0.333333
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4,0.108333
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2,0.303571
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,0.523810
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,0.261905
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,0.285714
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,0.000000
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,0.119048
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,0.011905
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2,0.488095

In [5]:
# 1.2. qsec_mm 피쳐값이 0.5보다 큰 값을 갖는 레코드 수
car[car['qsec_mm']>0.5].shape[0]

9

In [6]:
# carb 피쳐값에 대해서 25%, 50%, 75% 값 출력
car['carb'].describe()['25%'], car['carb'].describe()['50%'], car['carb'].describe()['75%']

(2.0, 2.0, 4.0)

In [7]:
np.quantile(car['carb'], q=0.25)

2.0

In [14]:
# disp로 그룹핑한 그룹별 mpg 평균값의 90퍼값
car.groupby('disp')['mpg'].apply(np.mean).quantile(0.9)

30.4

In [15]:
car['disp'].sort_values().index[:10]

Int64Index([19, 18, 17, 25, 27, 2, 20, 26, 31, 8], dtype='int64')

In [18]:
## disp 피쳐값에 대해서 오름차순 정렬 시 10번째 값으로 1~10위의 disp 값 변경
disp10번째값 = car['disp'].sort_values().values[9] # 140.8
상위10개인덱스 = car['disp'].sort_values().index[:10] # [19, 18, 17, 25, 27, 2, 20, 26, 31, 8]
car.loc[상위10개인덱스,'disp'] = disp10번째값
car['disp'].sort_values()

31    140.8
2     140.8
27    140.8
26    140.8
25    140.8
20    140.8
8     140.8
19    140.8
18    140.8
17    140.8
29    145.0
7     146.7
0     160.0
1     160.0
10    167.6
9     167.6
5     225.0
3     258.0
13    275.8
11    275.8
12    275.8
30    301.0
22    304.0
21    318.0
23    350.0
28    351.0
6     360.0
4     360.0
24    400.0
16    440.0
15    460.0
14    472.0
Name: disp, dtype: float64

In [19]:
## disp 피쳐값에 대해서 80이상의 값에 대한 평균 산출
car[car['disp']>=80]['disp'].mean()

243.16562499999998

In [27]:
disp80퍼값

350.8

In [31]:
disp80퍼값 =  car['disp'].quantile(0.8)
car[car['disp']>=disp80퍼값]['disp'].mean()

406.14285714285717

In [84]:
## mpg 피쳐값에 대해서 80% 량의 데이터를 추출 후 'mpg'가 20 이상인 값을 중앙값(median)으로 바꾸고 변경전, 변경 후 'mpg'의 표준편차 출력
from sklearn.model_selection import train_test_split

중앙값 = car['mpg'].median() # 19.2
추출, 나머지 = train_test_split(car['mpg'], train_size=0.8)
수정할인덱스 = 추출[추출.values>=20].index
변경전표준편차 = 추출[추출.values>=20].std()
추출[수정할인덱스] = 중앙값
변경후표준편차 = 추출.std()
변경전표준편차, 변경후표준편차

(4.274299517305304, 2.4530593144072155)